FROM ubuntu:21.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y cargo libssl-dev openssl pkg-config && \
    rm -rf /var/lib/apt/lists/*

COPY ./wait-for-it.sh /src/wait-for-it.sh
RUN chmod +x /src/wait-for-it.sh

COPY ./rust /src
WORKDIR /src/hedgewars-server

RUN cargo build --release --features "official-server"

CMD /src/wait-for-it.sh hedgewars-db:3306 && RUST_LOG=info ./target/release/hedgewars-server